In [2]:
import numpy as np
prime_array=np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.array([[1,2,3],[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [40]:
matrix = np.random.randint(0, 2, (50, 50), dtype=np.uint8)

In [18]:
arr=np.array([[1,2,3,5],[4,5,6,9]])
print(arr.shape)

(2, 4)


In [21]:
array_of_integers=np.array([0,1,2,3,4,5,6,7,8,9])
print("Dimensionsof'array_of_integers'=*",array_of_integers.ndim)

Dimensionsof'array_of_integers'=* 1


In [22]:
sample_2d_array=np.array([[1,2,3],[4,5,6]])
print("Dimensions of an 'sample_2d_array'=*",sample_2d_array.ndim)

Dimensions of an 'sample_2d_array'=* 2


In [32]:
array_of_int=np.array([0,1,2,3,4,5,6,7,8,9])
print(f"The total elements'array_of_int'=",{array_of_int.size})

The total elements'array_of_int'= {10}


In [33]:
sample_2d_array=np.array([[1,2,3],[4,5,6]])
print(f"The total elements'sample_2d_array'=",{sample_2d_array.size})

The total elements'sample_2d_array'= {6}


In [27]:
a=np.array([2,3,4])
print(a)
print(a.dtype)

[2 3 4]
int32


In [28]:
a=a.astype('float64')
print(a)
print(a.dtype)

[2. 3. 4.]
float64
